#!/bin/bash
# Archive historical markdown files from root to _archive/docs/historical/

set -e

ARCHIVE_DIR="_archive/docs/historical"
mkdir -p "$ARCHIVE_DIR"

# List of files to archive (historical/status/bug fix documentation)
files_to_archive=(
  "BUGS_FIXED_AND_E2E_STATUS.md"
  "BUGS_FIXED_SUMMARY.md"
  "BUILD_ERRORS_FIXED.md"
  "BUSINESS_CREATION_FLOW_ANALYSIS.md"
  "BUSINESS_CREATION_ROUTE_REMOVED.md"
  "CFP_BACKEND_ERROR_INVESTIGATION.md"
  "CFP_FLOW_BUGS_FIXED.md"
  "CFP_FLOW_COMPLETE_FIXES.md"
  "CFP_FLOW_ERRORS_FIXED.md"
  "CFP_FLOW_FIXES_APPLIED.md"
  "CFP_FLOW_FIXES_IMPLEMENTED.md"
  "CFP_FLOW_FIXES_PROPOSAL.md"
  "CFP_FLOW_FIXES_TEST_SUMMARY.md"
  "CFP_FLOW_IMPORT_FIX_SUMMARY.md"
  "CFP_LOGGING_IMPROVEMENTS.md"
  "CFP_STATUS_UPDATES_IMPLEMENTED.md"
  "CFP_STATUS_UPDATES_INTEGRATION_TESTS.md"
  "CFP_TEST_SUITE_SUMMARY.md"
  "CFP_TESTS_COMPLETE.md"
  "CFP_UX_ANALYSIS.md"
  "DTO_COMPONENT_DASHBOARD_MAPPING.md"
  "DTO_COVERAGE_ANALYSIS.md"
  "DTO_E2E_TEST_STRATEGY.md"
  "DTO_GROUND_TRUTH_ANALYSIS.md"
  "DTO_IMPLEMENTATION_COMPLETE.md"
  "DTO_INTEGRATION_TESTS.md"
  "DTO_LOGGING_STRATEGY.md"
  "DTO_PRODUCTION_READY_FIXES.md"
  "DTO_TEST_BUG_FIXES_ITERATIVE.md"
  "DTO_TEST_COVERAGE_ANALYSIS.md"
  "DTO_TEST_ITERATIVE_STRATEGY.md"
  "Holistic_Refactoring_Script.md"
  "LBDD_AUTOMATED_PROCESSING_LIVE_UPDATES.md"
  "LBDD_CFP_BUGS_FIXED_JAN_2025.md"
  "LBDD_CFP_BUGS_FOUND_JAN_2025.md"
  "LBDD_CFP_DTO_VERIFICATION.md"
  "LBDD_CFP_FLOW_BUGS_FOUND_2025.md"
  "LBDD_CFP_FLOW_BUGS_FOUND.md"
  "LBDD_CFP_FLOW_BUGS.md"
  "LBDD_CFP_FLOW_COMPLETE_2025.md"
  "LBDD_CFP_FLOW_MOCKED_FIRECRAWL.md"
  "LBDD_CFP_FLOW_OBSERVATIONS_2025.md"
  "LBDD_CFP_FLOW_OBSERVATIONS.md"
  "LBDD_CFP_FLOWS_ANALYSIS.md"
  "LBDD_CFP_PIPELINE_COMPLETE_OBSERVATIONS.md"
  "LBDD_CFP_PIPELINE_OBSERVATIONS.md"
  "LBDD_CFP_TEST_RESULTS_JAN_2025.md"
  "LBDD_UI_METRICS_UPDATE_REVIEW.md"
  "LEGACY_ARCHIVE_DEPENDENCY_AUDIT.md"
  "LEGACY_PROPERTY_MAPPING_DEPRECATION_PROPOSAL.md"
  "LEGACY_PROPERTY_MAPPING_DEPRECATION.md"
  "REFACTORING_ACTION_PLAN.md"
  "README_AUTO_REFACTOR.md"
  "README_REFACTORING.md"
  "SPARQL_REFACTORING_SUMMARY.md"
  "SPARQL_SERVICE_ANALYSIS.md"
  "SPARQL_SERVICE_FIX_PROPOSAL.md"
  "SPARQL_SERVICE_FIXES_APPLIED.md"
  "SPARQL_STRATEGY_RECOMMENDATIONS.md"
  "UX_COMPONENTS_CLEANUP.md"
  "WIKIDATA_SERVICE_MIGRATION_COMPLETE.md"
)

moved_count=0
skipped_count=0

# Move files
for file in "${files_to_archive[@]}"; do
  if [ -f "$file" ]; then
    echo "Moving $file to $ARCHIVE_DIR/"
    mv "$file" "$ARCHIVE_DIR/"
    ((moved_count++))
  else
    echo "Warning: $file not found, skipping"
    ((skipped_count++))
  fi
done

echo ""
echo "Archive complete!"
echo "  - Files moved: $moved_count"
echo "  - Files not found: $skipped_count"
echo "  - Archive location: $ARCHIVE_DIR/"


